//! **What a phone may ask for, and what it is told back.**
//!
//! # The principle that decides every field in this file
//!
//! **The counter is the authority. The phone submits an INTENT.**
//!
//! Only the counter assigns numbers, computes money, decides what the kitchen
//! has been told, prints and settles. That was right in v1 and it stays right;
//! what changed at P19 is that the intent now travels ten feet over the shop's
//! WiFi instead of to Mumbai and back (D9).
//!
//! So every type here is a *request*, never a result. There is no `total` a
//! phone can send, no `price`, no `bill_number`. Where one would be useful the
//! phone asks for the OPERATION — "10% off this line" — and the counter does
//! the arithmetic, checks the staff member's limit and answers.
//!
//! # These are types and nothing else
//!
//! This module has no logic, exactly as the rest of `mb-lan` has no business
//! rule: `magic-bill` applies an intent, because applying one means touching
//! the order lifecycle and the kitchen ledger, and mb-lan knows about neither.
//! The contract for a phone author is `docs/LAN_PROTOCOL.md`.

use serde::{Deserialize, Serialize};

/// One thing a phone is asking the counter to do.
///
/// **Every intent carries a client-generated `id`**, and that id is the whole
/// of the idempotency design: a waiter on a flaky connection retries, a phone
/// that lost a reply cannot know whether the intent landed, and the counter
/// answers a repeat with the ORIGINAL outcome rather than doing it twice.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Intent {
    /// Generated by the phone, unique for ever. A UUID or the device id plus a
    /// counter — the counter does not care, only that it never repeats.
    pub id: String,
    /// Which order this is about. Absent only for [`What::OpenOrder`], which is
    /// the intent that creates one.
    #[serde(default)]
    pub order_id: Option<String>,
    /// **The phone's clock**, in milliseconds since the epoch, and it is used
    /// for exactly one thing: deciding whether a queued intent is too old to
    /// apply without asking a person (see `Outcome::Held`). It never becomes a
    /// business day and never reaches a bill — D5 and audit B1 are why.
    pub at: i64,
    pub what: What,
}

/// The operations. Adding one is a variant here, a match arm in
/// `magic-bill`'s applier, and a paragraph in `LAN_PROTOCOL.md`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "do", rename_all = "snake_case")]
pub enum What {
    /// Start an order on a table. The counter claims the token and the bill
    /// number (D6, atomically) — never the phone.
    OpenOrder {
        order_type: String,
        table_id: Option<String>,
        covers: Option<u32>,
    },
    /// **No price, deliberately.** The counter looks the item up and freezes
    /// its own snapshot (P13's `ItemSnapshot`), so a phone holding a stale
    /// catalogue cannot sell yesterday's price.
    AddItem {
        item_id: String,
        /// A decimal string, parsed by `Qty::parse` on the counter. Not a
        /// float: D7 keeps floating point off the money path and a quantity
        /// multiplies a price.
        qty: String,
        note: Option<String>,
        #[serde(default)]
        modifiers: Vec<String>,
    },
    SetQty {
        line: usize,
        qty: String,
    },
    /// Compulsory reason — the same rule the counter's own void has had since
    /// P03, and for the same reason: audit B6.
    VoidItem {
        line: usize,
        reason: String,
    },
    SetOrderNote {
        note: Option<String>,
    },
    SetCustomer {
        customer_id: Option<String>,
    },
    SetCovers {
        covers: Option<u32>,
    },
    /// **A request, not an amount.** The counter checks the staff member's
    /// `max_discount_bp` (P11) and does its own arithmetic.
    RequestDiscount {
        line: Option<usize>,
        percent_bp: u32,
        reason: String,
    },
    /// Ask the kitchen to be told. **The counter decides the DELTA** —
    /// `KitchenLedger::pending` is the only thing allowed to, and a phone that
    /// computed its own would double-print on a retry. Crown jewel 2.
    SendToKitchen,
    MoveTable {
        table_id: String,
    },
    CancelOrder {
        reason: String,
    },
    /// Ask the counter to work the bill out. It comes back in
    /// [`Outcome::Ok`]'s order view, computed on the counter, always.
    RequestBill,
}

impl What {
    /// The name that goes in the audit trail and in a refusal.
    #[must_use]
    pub const fn name(&self) -> &'static str {
        match self {
            What::OpenOrder { .. } => "open an order",
            What::AddItem { .. } => "add an item",
            What::SetQty { .. } => "change a quantity",
            What::VoidItem { .. } => "void an item",
            What::SetOrderNote { .. } => "put a note on the order",
            What::SetCustomer { .. } => "put this on an account",
            What::SetCovers { .. } => "say how many are eating",
            What::RequestDiscount { .. } => "ask for a discount",
            What::SendToKitchen => "send to the kitchen",
            What::MoveTable { .. } => "move the order to another table",
            What::CancelOrder { .. } => "cancel the order",
            What::RequestBill => "ask for the bill",
        }
    }
}

/// What the counter did about it.
///
/// **Every variant carries a sentence a waiter can read.** A refusal that says
/// "could not save" is the finding and not the fix: the waiter has a customer
/// in front of them and needs to know whether to write it down (audit F8).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "outcome", rename_all = "snake_case")]
pub enum Outcome {
    /// Done. `order` is the counter's own view of the order afterwards —
    /// **including the money**, which the phone displays and never computes.
    Ok {
        order_id: String,
        /// Already formatted by `Money::to_plain_string`, like every other
        /// figure that crosses a boundary in this product (D39, R8).
        total: String,
        /// What the phone shows: line by line, in the counter's words.
        lines: Vec<LineView>,
        /// The token a waiter calls out, when there is one.
        token: Option<String>,
        /// Non-empty when the counter did something the phone did not ask for
        /// and has to be told about — "the cashier had already settled this".
        note: Option<String>,
    },
    /// The counter said no. The phone shows `message` and does not retry.
    Refused { message: String },
    /// **Not applied, and not lost.** A queued intent older than the shop's
    /// hold age waits for a person: v1 printed yesterday's tickets at 7 am and
    /// this is the rebuild of the fix it eventually grew.
    Held { message: String, batch_id: String },
}

impl Outcome {
    /// Whether the phone should stop retrying. True for everything: a refusal
    /// is final, a hold is a person's decision, and an `Ok` is done.
    #[must_use]
    pub const fn is_final(&self) -> bool {
        true
    }

    #[must_use]
    pub fn message(&self) -> String {
        match self {
            Outcome::Ok { note, .. } => note.clone().unwrap_or_default(),
            Outcome::Refused { message } | Outcome::Held { message, .. } => message.clone(),
        }
    }
}

/// One line, as a phone shows it. Every figure is a string the counter
/// formatted (R8) — the phone does no arithmetic on money, ever.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LineView {
    pub line: usize,
    pub name: String,
    pub qty: String,
    pub amount: String,
    pub note: Option<String>,
    /// True once the kitchen has been told about this much of it. The waiter
    /// needs to know before they offer to change it.
    pub sent_to_kitchen: bool,
}

/// A batch of intents a phone queued while it could not reach the counter.
///
/// **In order, and idempotent across the whole batch** — not per message. A
/// phone that retries a batch after getting half an answer must not double
/// half of it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Batch {
    pub intents: Vec<Intent>,
}

/// What happened to each one. **Per intent, never one status for the batch**:
/// a batch that reports a single result is a batch whose failures are
/// invisible.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BatchResult {
    pub outcomes: Vec<(String, Outcome)>,
    /// The whole thing in one sentence, for the phone's own screen: "38 of 40
    /// went through. 2 are waiting for somebody at the counter."
    pub says: String,
}

/// The catalogue a phone needs to take an order, and its version.
///
/// **The version is the whole point**: a phone asks with what it holds and is
/// told "unchanged" rather than being sent the menu again. A shop with 400
/// items on fifteen phones every reconnect is a shop whose WiFi is the
/// bottleneck.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Catalogue {
    pub version: String,
    pub items: Vec<CatalogueItem>,
    pub tables: Vec<CatalogueTable>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CatalogueItem {
    pub id: String,
    pub name: String,
    pub category: String,
    /// Formatted by the counter. It is shown, never used in a sum.
    pub price: String,
    /// Scope 3.9 — pushed the moment it changes, because a waiter selling a
    /// dish that ran out twenty minutes ago is the complaint this exists to
    /// prevent.
    pub is_available: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CatalogueTable {
    pub id: String,
    pub label: String,
    pub section: String,
    pub seats: u32,
    /// `free`, `open`, `bill_asked` — the same words the floor screen uses.
    pub state: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    /// **T5's half that lives in the types.** There is nowhere for a phone to
    /// put a price, a total or a discount amount — the shape refuses it before
    /// any code has to.
    #[test]
    fn a_phone_has_nowhere_to_put_money() {
        let json = serde_json::to_string(&Intent {
            id: "i1".to_owned(),
            order_id: Some("ord_1".to_owned()),
            at: 0,
            what: What::AddItem {
                item_id: "itm_dosa".to_owned(),
                qty: "2".to_owned(),
                note: None,
                modifiers: vec![],
            },
        })
        .expect("serialises");

        for forbidden in ["price", "total", "amount", "paise", "rate"] {
            assert!(
                !json.contains(forbidden),
                "an intent carries {forbidden}, which is a second money path"
            );
        }

        // And an intent that arrives WITH one is not rejected — it is parsed
        // and the extra field ignored, because refusing would break a floor
        // full of phones one version behind.
        let lying = r#"{"id":"i2","orderId":null,"at":0,
            "what":{"do":"add_item","item_id":"itm_dosa","qty":"1","note":null,
                    "modifiers":[],"total":"999.00"}}"#;
        let parsed: Intent = serde_json::from_str(lying).expect("a lying phone still parses");
        assert!(matches!(parsed.what, What::AddItem { .. }));
    }

    /// Every operation says what it is in words, because that string is what a
    /// refusal and an audit row are built from.
    #[test]
    fn every_operation_can_say_what_it_is() {
        let all = [
            What::OpenOrder { order_type: "dine_in".to_owned(), table_id: None, covers: None },
            What::AddItem { item_id: "i".to_owned(), qty: "1".to_owned(), note: None, modifiers: vec![] },
            What::SetQty { line: 0, qty: "1".to_owned() },
            What::VoidItem { line: 0, reason: "r".to_owned() },
            What::SetOrderNote { note: None },
            What::SetCustomer { customer_id: None },
            What::SetCovers { covers: None },
            What::RequestDiscount { line: None, percent_bp: 1000, reason: "r".to_owned() },
            What::SendToKitchen,
            What::MoveTable { table_id: "t".to_owned() },
            What::CancelOrder { reason: "r".to_owned() },
            What::RequestBill,
        ];
        let mut seen = std::collections::BTreeSet::new();
        for what in &all {
            let name = what.name();
            assert!(!name.is_empty());
            assert!(
                name.chars().next().is_some_and(char::is_lowercase),
                "{name} has to read inside a sentence: \"you may not {name}\""
            );
            assert!(seen.insert(name), "two operations share the name {name}");
        }
    }

    /// A refusal always has something a waiter can read.
    #[test]
    fn no_outcome_is_silent() {
        let refused = Outcome::Refused {
            message: "That table is being settled at the counter.".to_owned(),
        };
        assert!(!refused.message().is_empty());
        let held = Outcome::Held {
            message: "This is from yesterday.".to_owned(),
            batch_id: "b1".to_owned(),
        };
        assert!(!held.message().is_empty());
    }
}
