//! What a phone may ask for, and what it is told back.

use serde::{Deserialize, Serialize};

/// One thing a phone is asking the counter to do.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Intent {
    /// Generated by the phone, unique for ever.
    pub id: String,
    /// Which order this is about.
    #[serde(default)]
    pub order_id: Option<String>,
    /// The phone's clock, in milliseconds since the epoch, and it is used for exactly one
    /// thing: deciding whether a queued intent is too old to apply without asking a person (see
    /// `Outcome::Held`).
    pub at: i64,
    pub what: What,
}

/// The operations. Adding one is a variant here, a match arm in `magic-bill`'s applier, and a
/// paragraph in `LAN_PROTOCOL.md`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "do", rename_all = "snake_case")]
pub enum What {
    /// Start an order on a table.
    OpenOrder {
        order_type: String,
        table_id: Option<String>,
        covers: Option<u32>,
    },
    /// No price, deliberately. The counter looks the item up and freezes its own snapshot, so a
    /// phone holding a stale catalogue cannot sell yesterday's price.
    AddItem {
        item_id: String,
        /// A decimal string, parsed by `Qty::parse` on the counter.
        qty: String,
        note: Option<String>,
        #[serde(default)]
        modifiers: Vec<String>,
    },
    SetQty {
        line: usize,
        qty: String,
    },
    /// Compulsory reason.
    VoidItem {
        line: usize,
        reason: String,
    },
    SetOrderNote {
        note: Option<String>,
    },
    SetCustomer {
        customer_id: Option<String>,
    },
    SetCovers {
        covers: Option<u32>,
    },
    /// A request, not an amount.
    RequestDiscount {
        line: Option<usize>,
        percent_bp: u32,
        reason: String,
    },
    /// Ask the kitchen to be told.
    SendToKitchen,
    MoveTable {
        table_id: String,
    },
    CancelOrder {
        reason: String,
    },
    /// Ask the counter to work the bill out.
    RequestBill,
}

impl What {
    #[must_use]
    pub const fn name(&self) -> &'static str {
        match self {
            What::OpenOrder { .. } => "open an order",
            What::AddItem { .. } => "add an item",
            What::SetQty { .. } => "change a quantity",
            What::VoidItem { .. } => "void an item",
            What::SetOrderNote { .. } => "put a note on the order",
            What::SetCustomer { .. } => "put this on an account",
            What::SetCovers { .. } => "say how many are eating",
            What::RequestDiscount { .. } => "ask for a discount",
            What::SendToKitchen => "send to the kitchen",
            What::MoveTable { .. } => "move the order to another table",
            What::CancelOrder { .. } => "cancel the order",
            What::RequestBill => "ask for the bill",
        }
    }
}

/// What the counter did about it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "outcome", rename_all = "snake_case")]
pub enum Outcome {
    /// Done. `order` is the counter's own view of the order afterwards — including the money,
    /// which the phone displays and never computes.
    Ok {
        order_id: String,
        /// Already formatted by `Money::to_plain_string`, like every other figure that crosses
        /// a boundary in this product.
        total: String,
        /// What the phone shows: line by line, in the counter's words.
        lines: Vec<LineView>,
        /// The token a waiter calls out, when there is one.
        token: Option<String>,
        /// Non-empty when the counter did something the phone did not ask for and has to be
        /// told about — "the cashier had already settled this".
        note: Option<String>,
    },
    /// The counter said no.
    Refused { message: String },
    /// Not applied, and not lost.
    Held { message: String, batch_id: String },
}

impl Outcome {
    /// Whether the phone should stop retrying.
    #[must_use]
    pub const fn is_final(&self) -> bool {
        true
    }

    #[must_use]
    pub fn message(&self) -> String {
        match self {
            Outcome::Ok { note, .. } => note.clone().unwrap_or_default(),
            Outcome::Refused { message } | Outcome::Held { message, .. } => message.clone(),
        }
    }
}

/// One line, as a phone shows it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LineView {
    pub line: usize,
    pub name: String,
    pub qty: String,
    pub amount: String,
    pub note: Option<String>,
    /// True once the kitchen has been told about this much of it.
    pub sent_to_kitchen: bool,
}

/// A batch of intents a phone queued while it could not reach the counter.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Batch {
    pub intents: Vec<Intent>,
}

/// What happened to each one.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BatchResult {
    pub outcomes: Vec<(String, Outcome)>,
    /// The whole thing in one sentence, for the phone's own screen: "38 of 40 went through.
    pub says: String,
}

/// The catalogue a phone needs to take an order, and its version.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Catalogue {
    pub version: String,
    pub items: Vec<CatalogueItem>,
    pub tables: Vec<CatalogueTable>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CatalogueItem {
    pub id: String,
    pub name: String,
    pub category: String,
    /// Formatted by the counter.
    pub price: String,
    /// Pushed the moment it changes, because a waiter selling a dish that ran out twenty
    /// minutes ago is the complaint this exists to prevent.
    pub is_available: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CatalogueTable {
    pub id: String,
    pub label: String,
    pub section: String,
    pub seats: u32,
    /// `free`, `open`, `bill_asked` — the same words the floor screen uses.
    pub state: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_phone_has_nowhere_to_put_money() {
        let json = serde_json::to_string(&Intent {
            id: "i1".to_owned(),
            order_id: Some("ord_1".to_owned()),
            at: 0,
            what: What::AddItem {
                item_id: "itm_dosa".to_owned(),
                qty: "2".to_owned(),
                note: None,
                modifiers: vec![],
            },
        })
        .expect("serialises");

        for forbidden in ["price", "total", "amount", "paise", "rate"] {
            assert!(
                !json.contains(forbidden),
                "an intent carries {forbidden}, which is a second money path"
            );
        }

        // And an intent that arrives WITH one is not rejected — it is parsed and the extra
        // field ignored, because refusing would break a floor full of phones one version
        // behind.
        let lying = r#"{"id":"i2","orderId":null,"at":0,
            "what":{"do":"add_item","item_id":"itm_dosa","qty":"1","note":null,
                    "modifiers":[],"total":"999.00"}}"#;
        let parsed: Intent = serde_json::from_str(lying).expect("a lying phone still parses");
        assert!(matches!(parsed.what, What::AddItem { .. }));
    }

    #[test]
    fn every_operation_can_say_what_it_is() {
        let all = [
            What::OpenOrder {
                order_type: "dine_in".to_owned(),
                table_id: None,
                covers: None,
            },
            What::AddItem {
                item_id: "i".to_owned(),
                qty: "1".to_owned(),
                note: None,
                modifiers: vec![],
            },
            What::SetQty {
                line: 0,
                qty: "1".to_owned(),
            },
            What::VoidItem {
                line: 0,
                reason: "r".to_owned(),
            },
            What::SetOrderNote { note: None },
            What::SetCustomer { customer_id: None },
            What::SetCovers { covers: None },
            What::RequestDiscount {
                line: None,
                percent_bp: 1000,
                reason: "r".to_owned(),
            },
            What::SendToKitchen,
            What::MoveTable {
                table_id: "t".to_owned(),
            },
            What::CancelOrder {
                reason: "r".to_owned(),
            },
            What::RequestBill,
        ];
        let mut seen = std::collections::BTreeSet::new();
        for what in &all {
            let name = what.name();
            assert!(!name.is_empty());
            assert!(
                name.chars().next().is_some_and(char::is_lowercase),
                "{name} has to read inside a sentence: \"you may not {name}\""
            );
            assert!(seen.insert(name), "two operations share the name {name}");
        }
    }

    /// A refusal always has something a waiter can read.
    #[test]
    fn no_outcome_is_silent() {
        let refused = Outcome::Refused {
            message: "That table is being settled at the counter.".to_owned(),
        };
        assert!(!refused.message().is_empty());
        let held = Outcome::Held {
            message: "This is from yesterday.".to_owned(),
            batch_id: "b1".to_owned(),
        };
        assert!(!held.message().is_empty());
    }
}

// A settled bill travelling from a secondary till to the master.

/// A FACT, not a request.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Forwarded {
    /// The till that took the money.
    pub terminal_id: String,
    /// The till describing itself, so the master can create the row the first time it hears
    /// from one â a forwarded bill points at a terminal, and pairing makes a DEVICE row
    /// rather than a till.
    pub terminal_name: String,
    /// And declaring its series.
    pub series_prefix: String,
    /// The orders, as `mb_core::AnyOrder` — settled, voided or cancelled.
    pub orders: Vec<serde_json::Value>,
}

/// What the master did with a forwarded batch.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Receipt {
    /// `(order id, stored)`. `stored` is true both for one that was just written and for one
    /// that was already there — a repeat is a success, which is what lets a till retry for ever
    /// without thinking.
    pub stored: Vec<(String, bool)>,
    /// Anything the master could not store, with the sentence a person reads.
    pub refused: Vec<(String, String)>,
    /// The whole thing in one sentence, for the secondary's own screen.
    pub says: String,
}

impl Receipt {
    /// Whether every order in the batch is now on the master — which is the only condition
    /// under which the sender may forget them.
    #[must_use]
    pub fn all_stored(&self) -> bool {
        self.refused.is_empty() && self.stored.iter().all(|(_, ok)| *ok)
    }
}
